### ISSUE TITLE
Scroll for section only

### ISSUE THREAD

**Issue by promokit** [d4nyll/smartscroll#10]
Hi. 
Is it possible to have smartscroll for the section only, but not for whole page?

**Comment by d4nyll** [comment]
Yes, there's [Hybrid Scroll](http://d4nyll.github.io/smartscroll/hybrid-scroll/), but currently, it only works with a header (if you have a non-scrolling section at the bottom, it doesn't work).

I am planning on refining this feature towards the end of this month.

**Comment by promokit** [comment]
I want to clarify my question with following screenshot: 
https://www.dropbox.com/s/o1wxt56irkc9ljt/content-scroll.png
Is it possible to have a scroll for "content" part only?

**Comment by d4nyll** [comment]
No, it's not possible at the moment. I am adding it to the to-do / to-investigate list. Thanks for the suggestion.

**Comment by promokit** [comment]
Thank you ver much!

**Comment by d4nyll** [comment]
After much thought, the architecture change that would be required to do that would be too different from what it is at the present. So this feature won't be implemented on smartscroll.

You can, of course, do this is through an `iframe` though.

But again, thank you for your suggestion.
