### ISSUE TITLE
Question: Make `React` version?

### ISSUE THREAD

**Issue by pudgereyem** [d4nyll/smartscroll#27]
Hey @d4nyll, hope you're all good!
I'm thinking of making a smartscroll port for `React.js`.
Just wanted to ping you about it, if you'd want to discuss that or anything!

Peace!

**Comment by d4nyll** [comment]
Hey Victor! Feel free to port it! I'll add a note to your repository after its done.

I'm super busy at the moment but if you need help just send me an email and I'll try to respond quickly
