### ISSUE TITLE
How to do a split screen scroll?

### ISSUE THREAD

**Issue by angelaamongstrangers** [d4nyll/smartscroll#29]
Hi Daniel,

Thank you for smartscrool. It's great! I just wanted to ask if its possible to do a split screen smartscroll. One side is just normal scrolling with some text floating to the left, and another with using smartscroll and images. Whats happening with me now is that even if i dont include the left side text inside the section wrapper it is still affected by the smartscoll being used on the right side. I hope you can help me!

**Comment by d4nyll** [comment]
I haven't played around with split screen scrolling - I assume the scroll takes up the width of the viewport. If you can give me a more detailed example, I might have a play around with it when I get more time!
