### ISSUE TITLE
Hashes are being set 1 section ahead

### ISSUE THREAD

**Issue by cooperhu** [d4nyll/smartscroll#30]
I've noticed that when you scroll the hash of each section is one ahead. This is happening on my project as well as on the Demo page you set up. Any idea on what's causing this and if there is anyway to fix it? I'm thinking of using this plugin for my next project, but I would need the hashes to be correct. Other than this issue with the hashes, the plugin is pretty awesome! 

Any help is appreciated, thanks!

**Comment by aamir1995** [comment]
Same here :(

**Comment by karneaud** [comment]
+1

**Comment by d4nyll** [comment]
Thanks for reporting it. It's probably to do with this line - https://github.com/d4nyll/smartscroll/blob/master/smartscroll.js#L326 - I've had a lot of trouble with this actually. I'll look into it when I have more time to spare.

**Comment by a7madgamal** [comment]
this breaks the whole script :(

**Comment by a7madgamal** [comment]
changing line 331
`slideIndex + 1` to `slideIndex` seems to fix it, please confirm and I can send a pr :)

**Comment by d4nyll** [comment]
@a7madgamal You're more than welcomed to send a PR, that's the beauty of open-source right?! :slightly_smiling_face: 

But I'd need to review your PR before I'll merge it. I'll try to make some time towards the end of this month to do that, just making sure it works on different screen sizes and it behaves correctly after resizing events etc.

So please do submit the PR, just don't be discouraged if I can't review it straight away! I will try my best to review it ASAP.

**Comment by ionutchirica** [comment]
Any news about fixing this?

**Comment by d4nyll** [comment]
This has been fixed in Release [2.5.2](https://github.com/d4nyll/smartscroll/releases/tag/2.5.2) and published on [NPM](https://www.npmjs.com/package/smartscroll) and Bower.

@a7madgamal Was right, changing `slideIndex + 1` to `slideIndex` did fix things. Sorry it took so long to fix it, I've, unfortunately, always had things higher up on my priorities list.

**Comment by a7madgamal** [comment]
better late than never :)
glad I could help although I don't remember anything about it now lol
