### ISSUE TITLE
URL hash update based on scroll is not working. 

### ISSUE THREAD

**Issue by sabrinaazad** [d4nyll/smartscroll#39]
I am trying to use this plugin. I see the headerHash appear but it does not update as I scroll. I have attached pictures of what my code looks like and there are no console errors so I know the syntax is not the issue. Please help! Also, I have the three script files included below all my code right before the closing body tag. 

<script src="js/lethargy.min.js"></script>
<script src="https://rawgit.com/Olical/EventEmitter/master/EventEmitter.min.js"></script>
<script src="js/smartscroll.min.js"></script>

![screen shot 2017-12-19 at 1 46 04 pm](https://user-images.githubusercontent.com/5987627/34173361-344bc8b2-e4c3-11e7-8c15-9a34da8745ee.png)
![screen shot 2017-12-19 at 1 46 13 pm](https://user-images.githubusercontent.com/5987627/34173366-3780b34e-e4c3-11e7-87ba-f8767bd77e03.png)

**Comment by sabrinaazad** [comment]
UPDATE: So now the anchor is working but it is not reading the first data-hash="welcome" it starts at dog but is anchoring dog to the beginning of the website which is hashed welcome.

**Comment by sabrinaazad** [comment]
![screen shot 2017-12-19 at 2 56 31 pm](https://user-images.githubusercontent.com/5987627/34176193-1372cfdc-e4cd-11e7-9626-871f750bc7c6.png)
![screen shot 2017-12-19 at 2 56 16 pm](https://user-images.githubusercontent.com/5987627/34176197-151864b4-e4cd-11e7-90ae-e7935cea9bb7.png)

**Comment by d4nyll** [comment]
Your updated issue is related to #30, which has just now been fixed.

Also, make sure you put your `<div class="section">` divs inside the `<div class="section-wrapper">` div.
