### ISSUE TITLE
scroll method has hardcoded speed

### ISSUE THREAD

**Issue by havlasme** [d4nyll/smartscroll#50]
I've noticed that there is hardcoded animation speed in scroll method

https://github.com/d4nyll/smartscroll/blob/749a7e74f12e12452ba7a9e0445fddf7c747a8af/smartscroll.js#L277

https://github.com/d4nyll/smartscroll/blob/749a7e74f12e12452ba7a9e0445fddf7c747a8af/smartscroll.js#L279

I believe it should use `options.animationSpeed` instead of specifying value `700`.

**Comment by d4nyll** [comment]
You're right @tomashavlas! Thanks for the spot. Fixed it with a commit just now!
