### ISSUE TITLE
Hybrid Scrolling issue

### ISSUE THREAD

**Issue by itsacezon** [d4nyll/smartscroll#8]
I can't scroll to the portions after the section tagged for hybrid scrolling. It seems that I cannot go beyond the last panel of the section. Is there a fix to this?

**Comment by d4nyll** [comment]
This seems like a big issue, I will see if I can squeeze some time in this weekend and fix it, if not it'll have to wait til next month unfortunately.

**Comment by pudgereyem** [comment]
+1

It would be wonderful if we could get this to work. Since this is the case in the project I'm working on right now. I left a comment on your blog post; http://blog.danyll.com/smartscroll-jquery-scrolljacking-plugin/

Please tell me if this is something you're working on, and if I can help out.

**Comment by pudgereyem** [comment]
I solved this by adding another condition that checks distanceScrolled against the distance to where sectionWrapper ends. I opened up a pull request; https://github.com/d4nyll/smartscroll/pull/12

It works fine for me! Please take a look @d4nyll

Comment: I only changed smartscroll.js, since I didn't see any build task for creating the minified version.

**Comment by d4nyll** [comment]
@pudgereyem Apologies for the long time it took for me to review and merge it. Thank you very much for the PR, it has now been merged into version 2.0.1. Many many thanks for your time, it's very much appreciated!

**Comment by pudgereyem** [comment]
@d4nyll Awesome that you merged it in, glad to see the activity. Have you seen http://www.w3.org/TR/css-snappoints-1/#examples? – looks interesting. Blog post here; http://blog.teamtreehouse.com/css-scroll-snap-points

Feel free to add me on Skype, username; virremey.

**Comment by d4nyll** [comment]
@pudgereyem No I haven't seen it, thanks for sharing! It looks very interested at first glance, and I will definitely take a more detailed look at it.

Added!
